import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartDrawer } from "@/components/CartDrawer";
import LoginModal from "@/components/LoginModal";
import { ClientRoot } from "@/components/ClientRoot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Order Food & Groceries. Discover the best restaurants | Swiggy it!",
  description: "Generated by create next app",
  icons: {
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJQAAACUCAMAAABC4vDmAAAAjVBMVEX/UgD/////TwD/SwD/RQD/SAD/1cf/9vH/clD/kXf/5d7/xrv/xrj/WyD/OQD/PgD/+/n/zr//8ez/qY//u6n/YC7/elP/2c7/i2r/v7D/sp7/fFj/7OX/mID/hWT/tqD/dkv/sJf/VRD/Zzv/cEP/aUb/k3L/opD/qpz/uK//mHr/noH/o4n/YDX/qpZuFM35AAAEHElEQVR4nO2b23qiMBCAJQdQVk6KInhGW9uu9v0fb8GuVSCQCJngRf7bXvh/kzCZTKaDgUaj0Wg0Go1Go9FoXgiEyS8U922TgajnprtzODajyAzCZDEjLulXjJLhOrCMIvZ+k3p9eSFC3qOy0RXfDp1+tMgh8VlG/zFH6rcXpdNJg1JOdCRIpRKiC55STjij6pwwHQsoZUzmRJUTma/EnPJgKVpCsmna4GXGqQorb/qEUoadwn+F9Os5p+wrnEHHyvv7rFMWK+B9RZfPOxlGACqFDyLpqcrWBZQiUSsnw9jAZVFybulkrMA2O14+k6CKBB6QlNt28XJ2MNmKLng/bCVxbSyjFEQq5QZq5LpJ7R83EKHCG26ghgiPav9qQ+wq/o5qljKW8kOFjzwnntRYfq4i312lVhfpucrh5wOOlLGQHSr0xk+cPKmx7K1O37lOXClftpQncFXgSh0kf3+uQM3CkzLWcjcVGgicxVypRK4UPsqQCiVLcc8YEamRXCm6liAlu6Yip+5SsexrKfnoKDWJ557sU0bg5KuR8n3LMvfzC0C3SnRPoUs4vhGH2+S03gwHrkswxL0Bc0vhH6kBwncopYRiEJ8fqZ1YnoL6fSYoFbldTSm6gmkWpd/GOlyoRM4+wzCDK9cdFcefn58fp/Vo7lDPoxBmXiAixST7/uzx1wEgYKRFC6iAFcq3QsOOUhANITQTb77WMDlIt8KCXWqlUkI5vZHIke0kmKmakFziXenUCMqB6HCIXLKamEA0OFDLJuyNLUgvj8RdnPw3kCMQt+qh3zCBjmXX7iAl+SbzS/uOdXb0Qb0aoUv7o2YP9hrZfqsDFqXIaSsVAz7bti71joAPkW0fQkzIV6wBbhcqkMb+XarVroqAX5Fb5Sqgx6I7ePt8oEB3VA4ie+YkUD0+7I76gRyTwGRQVwQGSgZesls5C1IzsTDrc/AMOcwqIgDfUQ8KlBRANVITmOKOBXad0Xf85058QGyprbJhJbyr7OopZUr56qbNcLWwqpE6KZs1Q2n119lS0AfMI4zxErbUUuVQ3rCS1ZlSMdTcBpNqYcySso5qZypx+brMkjorDRSjM8SQWsH1hWvwzJIUKUspqQ6KlIcnbM97Lxbw0h/XBSClWZtVKXQTJQOeJVDa3Fo4K0xRd+i8ycnsYfGuVg23eP+tp9IOOfW9vWkvi5dTPxBnK09RD1Y1HX8fsnfAo24BE2XlJgvCfF2HnmDmwfoCffBrOgfWAn73ung51S8w6t2puoBW34uXg2jxarN+gUBloSqMMUU9nXllyMP/h8ANnj+Ldy9ipM9ytgYdbjeuUGGLhcetNWXLfybugHs9mf1e+2MVkJPnhdOLfHk38GxlSR7jlACeDUEmf7qBXk9Jo9FoNBqNRqPRyOEf5JA7dq7b1VMAAAAASUVORK5CYII="
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ClientRoot>
          {children}
          <CartDrawer />
          <LoginModal />
        </ClientRoot>
      </body>
    </html>
  );
}
